{
 "title": "Solar Energy Trend Production",
 "description": "Photovoltaic trend production by day",
 "tags": [
  "influxdb",
  "photovoltaic",
  "trend"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "Power generated by day",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Power generated by day",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "device_status",
     "query": "SELECT last(\"today_generated\") FROM \"device_status\" WHERE (\"today_generated\" != 0 AND \"poller\" = 'pypeimar' AND \"hostname\" = 'inverter') GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "today_generated" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "inverter" },
      { "condition": "AND", "key": "poller", "operator": "=", "value": "pypeimar" }
     ]
    }
   ]
  },
  {
   "title": "Running time by day",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "alias": "Running time by day",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "device_status",
     "query": "SELECT last(\"today_running_time\") FROM \"device_status\" WHERE (\"today_running_time\" != 0 AND \"hostname\" = 'inverter' AND \"poller\" = 'pypeimar') GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "today_generated" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "inverter" },
      { "condition": "AND", "key": "poller", "operator": "=", "value": "pypeimar" }
     ]
    }
   ]
  },
  {
   "title": "Savings by day",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "alias": "Savings by day",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "device_status",
     "query": "SELECT last(\"today_generated\") * 0.29 FROM \"device_status\" WHERE (\"today_generated\" != 0 AND \"poller\" = 'pypeimar' AND \"hostname\" = 'inverter') GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "today_generated" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " * 0.21" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "inverter" },
      { "condition": "AND", "key": "poller", "operator": "=", "value": "pypeimar" }
     ]
    }
   ]
  }
 ]
}