{
 "title": "Solar Energy Analysis (current metrics)",
 "description": "Power home's consumed vs Photovoltaic Production",
 "tags": [
  "influxdb",
  "analysis",
  "photovoltaic",
  "current metrics"
 ],
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "Solar System Diagram",
   "type": "larona-epict-panel",
   "description": "Blue: Home's Power Consumed<br/>\nOrange: Solar Power Produced<br/>\nGreen/Red: Energy balance",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "Home's Power Consumed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "emeter",
     "query": "SELECT last(\"power\") FROM \"emeter\" WHERE (\"poller\" = 'pyshelly' AND \"hostname\" = 'shellyem') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "poller", "operator": "=", "value": "pyshelly" },
      { "condition": "AND", "key": "hostname", "operator": "=", "value": "shellyem" }
     ]
    },
    {
     "alias": "Solar Power Produced",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "device_status",
     "select": [
      [
       { "params": [ "ac_out_grid_power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "poller", "operator": "=", "value": "pypeimar" },
      { "condition": "AND", "key": "hostname", "operator": "=", "value": "inverter" }
     ]
    }
   ]
  },
  {
   "title": "Home's Power Consumed vs Solar Power Produced",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Home's Power Consumed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "emeter",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "poller", "operator": "=", "value": "pyshelly" },
      { "condition": "AND", "key": "hostname", "operator": "=", "value": "shellyem" }
     ]
    },
    {
     "alias": "Solar Power Produced",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "device_status",
     "select": [
      [
       { "params": [ "ac_out_grid_power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "poller", "operator": "=", "value": "pypeimar" },
      { "condition": "AND", "key": "hostname", "operator": "=", "value": "inverter" }
     ]
    }
   ]
  },
  {
   "title": "Current Power",
   "type": "timeseries",
   "description": "Power balance = (Solar Power Produced - Home's Power Consumed)<br/><br/>\nPositive value = excess power transferred to the grid<br/>\nNegative value = missing power taken from the grid<br/>",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Home's Power Consumed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "emeter",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "poller", "operator": "=", "value": "pyshelly" },
      { "condition": "AND", "key": "hostname", "operator": "=", "value": "shellyem" }
     ]
    },
    {
     "alias": "Solar Power Produced",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "device_status",
     "select": [
      [
       { "params": [ "ac_out_grid_power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "poller", "operator": "=", "value": "pypeimar" },
      { "condition": "AND", "key": "hostname", "operator": "=", "value": "inverter" }
     ]
    }
   ]
  },
  {
   "title": "Watt-hour produced for every hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Solar Energy Produced",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "device_status",
     "select": [
      [
       { "params": [ "today_generated" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "poller", "operator": "=", "value": "pypeimar" },
      { "condition": "AND", "key": "hostname", "operator": "=", "value": "inverter" }
     ]
    }
   ]
  }
 ]
}