{
 "title": "Solar Energy Infrastructure",
 "description": "Photovoltaic Production by Peimar Inverter single-phase",
 "tags": [
  "peimar inverter",
  "photovoltaic",
  "influxdb",
  "python"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "influxdb" },
   {
    "name": "poller",
    "label": "Poller",
    "query": "SHOW TAG VALUES FROM alive WITH KEY=poller"
   },
   {
    "name": "server",
    "label": "Server",
    "query": "SHOW TAG VALUES FROM alive WITH KEY=hostname WHERE poller =~ /$poller/"
   },
   {
    "name": "country",
    "label": "Country",
    "query": "SHOW TAG VALUES FROM \"openweathermap\" WITH KEY = \"sys_country\""
   },
   {
    "name": "city",
    "label": "City",
    "query": "SHOW TAG VALUES FROM \"openweathermap\" WITH KEY = \"name\""
   }
  ]
 },
 "panels": [
  { "title": "Inverter Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Inverter Alive",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Alive",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alive",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "poller", "operator": "=~", "value": "/^$poller$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Inverter Alive History",
   "type": "graph",
   "description": "Night time hourly (No production): 21:30 - 05:30",
   "gridPos": { "h": 3, "w": 18, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Alive",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alive",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "poller", "operator": "=~", "value": "/^$poller$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total generated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total generated",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "device_status",
     "query": "SELECT last(\"tot_generated\") FROM \"device_status\" WHERE (\"hostname\" = 'inverter' AND \"poller\" = 'pypeimar') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "tot_generated" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "poller", "operator": "=~", "value": "/^$poller$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Running Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total Running Time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "device_status",
     "select": [
      [
       { "params": [ "tot_running_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "poller", "operator": "=~", "value": "/^$poller$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Today generated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Today generated",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "device_status",
     "select": [
      [
       { "params": [ "today_generated" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "poller", "operator": "=~", "value": "/^$poller$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Today Running Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Today Running Time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "device_status",
     "select": [
      [
       { "params": [ "today_running_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "poller", "operator": "=~", "value": "/^$poller$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Savings",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total Savings",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "device_status",
     "select": [
      [
       { "params": [ "tot_generated" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 0.29" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "poller", "operator": "=~", "value": "/^$poller$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Today Savings",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Today Savings",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "device_status",
     "query": "SELECT last(\"today_generated\")  * 0.23 FROM \"device_status\" WHERE (\"hostname\" =~ /^$server$/ AND \"poller\" =~ /^$poller$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "today_generated" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 0.29" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "poller", "operator": "=~", "value": "/^$poller$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Total CO2 emission reduction",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total CO2 emission reduction",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "device_status",
     "select": [
      [
       { "params": [ "co2_reduction" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "poller", "operator": "=~", "value": "/^$poller$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  { "title": "Weather $city, $country", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_country" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openweathermap",
     "select": [
      [
       { "params": [ "main_temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  },
  {
   "title": "Wind speed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openweathermap",
     "select": [
      [
       { "params": [ "wind_speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  },
  {
   "title": "Wind direction",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openweathermap",
     "select": [
      [
       { "params": [ "wind_deg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  },
  {
   "title": "Atmospheric pressure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openweathermap",
     "select": [
      [
       { "params": [ "main_pressure" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  },
  {
   "title": "Weather condition",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 8 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "openweathermap",
     "select": [
      [
       { "params": [ "weather_0_description" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sys_country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  },
  {
   "title": "Sunrise time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 8 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openweathermap",
     "select": [
      [
       { "params": [ "sys_sunrise" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "sys_country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  },
  {
   "title": "Cloudiness",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openweathermap",
     "select": [
      [
       { "params": [ "clouds_all" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openweathermap",
     "select": [
      [
       { "params": [ "main_humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  },
  {
   "title": "Sunset time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 11 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openweathermap",
     "select": [
      [
       { "params": [ "sys_sunset" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "sys_country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  },
  { "title": "Inverter DC Input", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "PV1 Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "PV1 Voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "device_status",
     "select": [
      [
       { "params": [ "dc_in_pv1_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "poller", "operator": "=~", "value": "/^$poller$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "PV1 Voltage History",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "yaxes": [
    { "format": "volt", "label": "Volt" }
   ],
   "targets": [
    {
     "alias": "PV1 Voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "device_status",
     "select": [
      [
       { "params": [ "dc_in_pv1_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "poller", "operator": "=~", "value": "/^$poller$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "PV1 Current History",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "yaxes": [
    { "format": "amp", "label": "Ampere" }
   ],
   "targets": [
    {
     "alias": "PV1 Current",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "device_status",
     "select": [
      [
       { "params": [ "dc_in_pv1_current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "poller", "operator": "=~", "value": "/^$poller$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "PV1 Current",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "PV1 Current",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "device_status",
     "select": [
      [
       { "params": [ "dc_in_pv1_current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "poller", "operator": "=~", "value": "/^$poller$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  { "title": "Inverter AC Output", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Grid-connected Power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Grid-connected Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "device_status",
     "select": [
      [
       { "params": [ "ac_out_grid_power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "poller", "operator": "=~", "value": "/^$poller$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Grid-connected Power History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 4, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "yaxes": [
    { "format": "kwatt", "label": "Watt" }
   ],
   "targets": [
    {
     "alias": "Grid-connected Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "device_status",
     "select": [
      [
       { "params": [ "ac_out_grid_power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "poller", "operator": "=~", "value": "/^$poller$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Grid-connected Frequency History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "yaxes": [
    { "format": "rothz", "label": "Hertz" }
   ],
   "targets": [
    {
     "alias": "Grid-connected Frequency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "device_status",
     "select": [
      [
       { "params": [ "ac_out_grid_frequency" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "poller", "operator": "=~", "value": "/^$poller$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Grid-connected Frequency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Grid-connected Frequency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "device_status",
     "select": [
      [
       { "params": [ "ac_out_grid_frequency" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "poller", "operator": "=~", "value": "/^$poller$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Line1 Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Line1 Voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "device_status",
     "select": [
      [
       { "params": [ "line1_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "poller", "operator": "=~", "value": "/^$poller$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Line1 Voltage History",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "yaxes": [
    { "format": "volt", "label": "Volt" }
   ],
   "targets": [
    {
     "alias": "Line1 Voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "device_status",
     "select": [
      [
       { "params": [ "line1_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "poller", "operator": "=~", "value": "/^$poller$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Line1 Current History",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "yaxes": [
    { "format": "amp", "label": "Ampere" }
   ],
   "targets": [
    {
     "alias": "Line1 Current",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "device_status",
     "select": [
      [
       { "params": [ "line1_current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "poller", "operator": "=~", "value": "/^$poller$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Line1 Current",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Line1 Current",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "device_status",
     "select": [
      [
       { "params": [ "line1_current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "poller", "operator": "=~", "value": "/^$poller$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  { "title": "Inverter Other Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Bus Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Bus Voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "device_status",
     "select": [
      [
       { "params": [ "bus_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "poller", "operator": "=~", "value": "/^$poller$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Bus Voltage History",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "yaxes": [
    { "format": "volt", "label": "Volt" }
   ],
   "targets": [
    {
     "alias": "Bus Voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "device_status",
     "select": [
      [
       { "params": [ "bus_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "poller", "operator": "=~", "value": "/^$poller$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Device Temperature History",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius", "label": "° Celsius" }
   ],
   "targets": [
    {
     "alias": "Device Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "device_status",
     "select": [
      [
       { "params": [ "device_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "poller", "operator": "=~", "value": "/^$poller$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Device Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Device Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "device_status",
     "select": [
      [
       { "params": [ "device_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "poller", "operator": "=~", "value": "/^$poller$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  }
 ]
}